export const Images = {
  GET_IMAGES: 'GET_IMAGES',
  GET_IMAGES_SUCCESS: 'GET_IMAGES_SUCCESS',
  GET_IMAGES_FAILURE: 'GET_IMAGES_FAILURE',
  SET_SELECTED_IMAGE: 'SET_SELECTED_IMAGE',
}

export const Search = {
  SET_TAGS: 'SET_TAGS',
  SET_TAG_MODE: 'SET_TAG_MODE',
}

